builds:
  - targets:
      - windows_amd64
      - windows_arm
      - windows_arm64
      - linux_amd64
      - linux_arm
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    format_overrides:
      - goos: windows
        format: zip